// lib/services/firebase/firebase_service.dart

import 'package:firebase_core/firebase_core.dart';
// import '../../firebase_options.dart'; // generated by flutterfire configure

class FirebaseService {
  static Future<void> initialize() async {
    await Firebase.initializeApp(
      // options: DefaultFirebaseOptions.currentPlatform,
    );
  }
}
